# Generated by Django 3.1.4 on 2020-12-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalGalapagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalmodel',
            name='imagenAnimal',
            field=models.ImageField(default=1, upload_to='AnimalImagenes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animalmodel',
            name='idAnimal',
            field=models.CharField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
