# Generated by Django 3.1.4 on 2020-12-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalGalapagos', '0002_auto_20201225_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalmodel',
            name='nombreTecnico',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
