# Generated by Django 3.1.4 on 2021-01-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalGalapagos', '0003_animalmodel_nombretecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAnimal', models.CharField(max_length=254)),
                ('imagenAnimal', models.ImageField(upload_to='ImagenesPrueba/')),
                ('predictLabel', models.CharField(max_length=254)),
            ],
        ),
    ]
