# Generated by Django 3.1.4 on 2021-01-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalGalapagos', '0004_animalentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalInfo',
            fields=[
                ('idAnimal', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('imagenAnimal', models.ImageField(upload_to='AnimalImagenes/')),
                ('nombreAnimal', models.CharField(max_length=254)),
                ('nombreTecnico', models.CharField(default=None, max_length=100)),
                ('idCategoria', models.CharField(default=None, max_length=100)),
                ('categoria', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AnimalModel',
        ),
    ]
