# Generated by Django 3.1.4 on 2021-01-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalGalapagos', '0005_auto_20210118_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalModel',
            fields=[
                ('idA', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('idAnimal', models.CharField(max_length=254)),
                ('imagenAnimal', models.ImageField(upload_to='AnimalImagenes/')),
                ('nombreAnimal', models.CharField(max_length=254)),
                ('nombreTecnico', models.CharField(default=None, max_length=100)),
                ('idCategoria', models.CharField(default=None, max_length=100)),
                ('categoria', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
